### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by JamieSinn** [mdlayher/arp#11]
Currently I need to listen for arp requests sent, and the raw depend fails to work on windows.

Possible to implement?

**Comment by mdlayher** [comment]
At one point, someone was working on Windows support for my raw sockets package. I don't know anything about Windows networking myself, unfortunately.

**Comment by alexbrainman** [comment]
@JamieSinn would something like https://stackoverflow.com/questions/43434765/sending-arp-request-by-calling-windows-dlls-inside-go-doesnt-work/43445375#43445375 do?

Alex

**Comment by JamieSinn** [comment]
I currently need to listen for an arp request on the go side, not send out out, which is my current dilemma.  The code you showed is the arp request being sent, I need to listen for it instead.

**Comment by alexbrainman** [comment]
> I currently need to listen for an arp request

Fair enough.

Alex

**Comment by mdlayher** [comment]
Closing because this is actually an issue for https://github.com/mdlayher/raw.
