### ISSUE TITLE
go generate produces error

### ISSUE THREAD

**Issue by miekg** [mdlayher/arp#16]
Hi thanks for this package. 

I was looking through the source and seeing that string.go and packet.go are generated (this comes from the go std lib I assume) as such 'go generate' does not work:

```
packet.go:26: running "stringer": exec: "stringer": executable file not found in $PATH
```
string.go also has some lint issues; I don't know if you want to keep this "this is generated code" in these files or clean them up?

**Comment by dominikh** [comment]
`stringer` is golang.org/x/tools/cmd/stringer and needs to be available on your PATH for that particular `go generate` invocation to work. 

`string.go` *is* generated code and as such should keep its header. Golint will complain about the leading underscores no doubt, but those are used by `stringer` intentionally, to avoid naming conflicts.

**Comment by mdlayher** [comment]
The newest stringer utility will add the "this is generated code" header that golint now ignores, so I've fixed that up!  Looks like this can be closed, but feel free to comment if you run into anything strange.
