### ISSUE TITLE
Support infiniband device

### ISSUE THREAD

**Issue by jcatana** [mdlayher/arp#18]
Trying to use a downsteam package that references this repo. I ran into an issue using IP over Infiniband device type in a mix ethernet/infiniband environment.
```
 ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc mq state UP mode DEFAULT group default qlen 256
    link/infiniband 20:00:00:67:fe:80:00:00:00:00:00:00:e0:07:1b:ff:ff:7d:e2:e8 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
```
Infiniband devices use 12 digit mac addresses and this probably unnecessary sanity check in packet.go causes error. 
Lines 90-92:
```
	if len(srcHW) != len(dstHW) {
		return nil, ErrInvalidHardwareAddr
	}
```
It assumes all MAC addresses are 6 character.
Removing the check and recompiling allowed downstream Metallb to work on my IP over Infiniband interconnects.

**Comment by mdlayher** [comment]
Neat. I'm good with that. Mind sending a PR?

**Comment by mdlayher** [comment]
Actually, why would that check cause an issue? The surrounding code just checks for MAC addresses of at least length 6.

**Comment by jcatana** [comment]
Yeah, that is fine, but the `if len(srcHW) != len(dstHW)` fails it . My source is 12 and dst is 6

**Comment by mdlayher** [comment]
Apologies, I haven't ever tried that. How does that work? I'd expect that you'd be ARPing to another IPoIB device on the other side.

The ARP packet allocates enough space for the length of the source address at the moment, so the 6 empty bytes on the destination are just ignored?

I'm happy to loosen the restriction, I'd just like to understand what's going on here. If you have some links, that'd be helpful.

**Comment by mdlayher** [comment]
In addition, this RFC seems to indicate both addresses would be 20 bytes: https://tools.ietf.org/html/rfc4391#section-9.2.

**Comment by jcatana** [comment]
Maybe it's upstream for you in "net" because I think that's how you are getting MAC address.
How can I help debug this and see what is being compared at that point? Just add fmt module and print it out? I've tried but I'm fairly bad at go.

**Comment by dacrystal** [comment]
From MetalLB: 
https://github.com/danderson/metallb/blob/30e6f68bade331367ddb3a772593d137af21e4d8/internal/layer2/arp.go#L52

```go
pkt, err := arp.NewPacket(op, a.hardwareAddr, ip, ethernet.Broadcast, ip)
```

As from the above,  it use ethernet.Broadcast as dstHW. And that's why it always fail for IP over Infiniband( 20bytes)

I belief removing the check would resolve the issue or check for destHW is not equal to ethernet.Broadcast too.

**Comment by mdlayher** [comment]
Let me know if this is all set now, thanks!
